### ISSUE TITLE
F0115 17:59:41.405607 17526 nonoverlapping_range_map.h:122] Check failed: predecessor->first.second <= low 

### ISSUE THREAD

**Issue by wayneicy** [google/autofdo#61] opened 2018-01-15 10:05 UTC
my command is ./create_gcov --binary=./bs.se --profile=./perf.data --gcov=bs.se.gcov -gcov_version=1
F0115 17:59:41.405607 17526 nonoverlapping_range_map.h:122] Check failed: predecessor->first.second <= low 
*** Check failure stack trace: ***
    @           0x4484d3  google::LogMessage::SendToLog()
    @           0x446461  google::LogMessage::Flush()
    @           0x448e39  google::LogMessageFatal::~LogMessageFatal()
    @           0x4559f5  autofdo::NonOverlappingRangeMap<>::InsertRange()
    @           0x453767  autofdo::InlineStackHandler::PopulateSubprogramsByAddress()
    @           0x40a2dc  autofdo::Google3Addr2line::Prepare()
    @           0x40986e  autofdo::Addr2line::CreateWithSampledFunctions()
    @           0x415b78  autofdo::ProfileCreator::ComputeProfile()
    @           0x415fcc  autofdo::ProfileCreator::CreateProfileFromSample()
    @           0x408158  main
    @     0x7fb1e9febbd5  __libc_start_main
    @           0x4093dd  (unknown)
    @              (nil)  (unknown)
Aborted

**Comment by danielcdh** [comment] 2018-01-16 17:41
This must be related to the debug info in bs.se. How did you compile that binary? It would be useful if you can upload both bs.se and perf.data so that we could debug.

**Comment by wayneicy** [comment] 2018-01-17 05:30
My cppflags is 
-g -finline-functions -W -Wall -pipe -O3 -finline-limit=100000 --param large-function-growth=100000 --param inline-unit-growth=100000 -Wl,-rpath /home/
     work/gcc5/lib64
[perf.data.zip](https://github.com/google/autofdo/files/1637828/perf.data.zip)

perf.data.zip is my perf.data

**Comment by danielcdh** [comment] 2018-01-17 16:13
The flags looks fine. Please also include the binary file to reproduce the problem.

**Comment by wayneicy** [comment] 2018-01-18 02:37
it's a little big....
you can cat bs.se.*.tar.gz > bs.se.tar.gz，and then unzip it，thanks

[bs.se.00.tar.gz](https://github.com/google/autofdo/files/1641378/bs.se.00.tar.gz)
[bs.se.01.tar.gz](https://github.com/google/autofdo/files/1641379/bs.se.01.tar.gz)
[bs.se.02.tar.gz](https://github.com/google/autofdo/files/1641380/bs.se.02.tar.gz)
[bs.se.03.tar.gz](https://github.com/google/autofdo/files/1641399/bs.se.03.tar.gz)
[bs.se.04.tar.gz](https://github.com/google/autofdo/files/1641388/bs.se.04.tar.gz)
[bs.se.05.tar.gz](https://github.com/google/autofdo/files/1641389/bs.se.05.tar.gz)
[bs.se.06.tar.gz](https://github.com/google/autofdo/files/1641390/bs.se.06.tar.gz)
[bs.se.07.tar.gz](https://github.com/google/autofdo/files/1641391/bs.se.07.tar.gz)
[bs.se.08.tar.gz](https://github.com/google/autofdo/files/1641392/bs.se.08.tar.gz)
[bs.se.09.tar.gz](https://github.com/google/autofdo/files/1641393/bs.se.09.tar.gz)
[bs.se.10.tar.gz](https://github.com/google/autofdo/files/1641394/bs.se.10.tar.gz)

**Comment by danielcdh** [comment] 2018-01-19 18:06
problem reproduced. This should be a bug in the current symbolizer. Internally, we have already switched to llvm symbolizer. I manually verified that with llvm-symbolizer, the problem is gone. I think the right solution would be porting llvm-symbolizer here. I will consult about how to prioritize this and set an ETA. At the same time, if this is emergent issue, feel free to send merge request to fix this in the current symbolizer.

**Comment by wayneicy** [comment] 2018-01-21 14:34
Thank you！ This is an emergent issue, please send a merge request to fix this in the current symbolizer.

**Comment by danielcdh** [comment] 2018-01-22 21:56
Sorry if my previous reply is unclear. This problem is not blocking us as we already moved to llvm symbolizer. And there is fix planned for the open-source version: porting llvm-symbolizer into github. As a result, we won't have the bandwidth to fix the current symbolizer. But we welcome contribution to fix the current symbolizer.

**Comment by danielcdh** [comment] 2018-04-16 01:07
With https://github.com/google/autofdo/pull/65 merged, this problem should have been fixed. Please reopen if otherwise.

**Closed by danielcdh** 2018-04-16 01:07 UTC

**Comment by derek-zhang** [comment] 2019-08-05 12:14
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff7b502d9 in __GI_abort () at abort.c:89
#2  0x00000000004f812e in google::DumpStackTraceAndExit () at glog/src/utilities.cc:147
#3  0x00000000004f1803 in google::LogMessage::Fail () at glog/src/logging.cc:1458
#4  0x00000000004f1769 in google::LogMessage::SendToLog (this=0x7fffffffd490) at glog/src/logging.cc:1412
#5  0x00000000004f119e in google::LogMessage::Flush (this=0x7fffffffd490) at glog/src/logging.cc:1281
#6  0x00000000004f3d66 in google::LogMessageFatal::~LogMessageFatal (this=0x7fffffffd490, __in_chrg=<optimized out>) at glog/src/logging.cc:1984
#7  0x00000000005036b2 in autofdo::NonOverlappingRangeMap<autofdo::SubprogramInfo*>::InsertRange (this=0x78a72188, low=27973855, high=27973871,
    value=@0x7fffffffd610: 0x5452f980) at ./symbolize/nonoverlapping_range_map.h:122
#8  0x0000000000500ed1 in autofdo::NonOverlappingRangeMap<autofdo::SubprogramInfo*>::InsertRangeList (this=0x78a72188, range_list=...,
    value=@0x7fffffffd610: 0x5452f980) at ./symbolize/nonoverlapping_range_map.h:100
#9  0x00000000004feb89 in autofdo::InlineStackHandler::PopulateSubprogramsByAddress (this=0x78a720e0) at symbolize/addr2line_inlinestack.cc:582
#10 0x0000000000411b89 in autofdo::Google3Addr2line::Prepare (this=0x78a46580) at addr2line.cc:177
#11 0x0000000000411186 in autofdo::Addr2line::CreateWithSampledFunctions (binary_name=..., sampled_functions=0x7fffffffdb00) at addr2line.cc:67
#12 0x0000000000429025 in autofdo::ProfileCreator::ComputeProfile (this=0x7fffffffe4f0, symbol_map=0x7fffffffdbc0) at profile_creator.cc:147
#13 0x0000000000428b57 in autofdo::ProfileCreator::CreateProfile (this=0x7fffffffe4f0, input_profile_name=..., profiler=..., writer=0x7fffffffe510,
    output_profile_name=...) at profile_creator.cc:111
#14 0x00000000004531f0 in main (argc=1, argv=0x7fffffffe650) at create_gcov.cc:34

Hi I still run into this error with latest master autofdo
could you give me some help, thank you
